---

- name: import base tasks
  ansible.builtin.import_tasks: base.yml

- name: import userconfig tasks
  ansible.builtin.import_tasks: userconfig.yml

- name: import ntp tasks
  ansible.builtin.import_tasks: ntp.yml

- name: import locale tasks
  ansible.builtin.import_tasks: locale.yml

- name: import fonts tasks
  ansible.builtin.import_tasks: fonts.yml

- name: import tlp tasks
  ansible.builtin.import_tasks: tlp.yml