---

- name: Install linux and headers
  community.general.pacman:
    name:
      - linux
      - linux-headers
    state: present

- name: Install required packages for UKI Secure Boot
  community.general.pacman:
    name:
      - mkinitcpio
      - sbctl
      - systemd-ukify
    state: present 
  register: task_result
  until: task_result is success      

- name: Push mkinitcpio configuration and regenerate initramfs
  ansible.builtin.template:
    src: mkinitcpio.conf.j2
    dest: /etc/mkinitcpio.conf
  notify:
    - regenerate initramfs
    
- name: Determine cryptdevice uuid
  ansible.builtin.command: "blkid -s PARTUUID -o value {{ cryptdevice }}"
  register: blkid_output

- name: Set uuid fact
  ansible.builtin.set_fact:
    crypt_uuid: "{{ blkid_output.stdout}}"

- name: Push cmdline config 
  ansible.builtin.template:
    src: cmdline.j2
    dest: /etc/kernel/cmdline
  notify:
    - regenerate initramfs

- name: push pacman hook for secure boot
  ansible.builtin.template:
    src: 95-systemd-boot.hook.j2
    dest: /etc/pacman.d/hooks/95-systemd-boot.hook

