---

- name: Install w3m
  community.general.pacman: name=w3m state=present
  tags:
    - w3m

- name: Install firefox
  community.general.pacman: name=firefox state=present
  tags:
    - firefox
    
- name: Install qutebrowser
  community.general.pacman: name=qutebrowser state=present
  tags:
    - qutebrowser