---

- name: Install pywall and components
  community.general.pacman:
    name:
     - python-pywal
     - python-pywalfox

    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
