---

- name: Install macchanger
  community.general.pacman: name=macchanger state=present
  notify:
    - rkhunter propupdate

- name: Create systemd unit for macchanger
  ansible.builtin.copy: src=macspoof@.service dest=/etc/systemd/system/

- name: Enable macspoof for all interfaces
  ansible.builtin.service: name=macspoof@{{ item }}.service enabled=true
  with_items:
    - "{{ ansible_interfaces }}"
  when: 
    - item != 'lo'
    - item != 'tailscale0'
    - item != 'virbr0'
