---

- name: Clone user dotfiles
  ansible.builtin.git:
    repo: "{{ dotfiles.url }}"
    dest: "{{ dotfiles.destination }}"
    accept_hostkey: true
    update: true
    force: true
  become: true
  become_user: "{{ user.name }}"

#- name: Install user dotfiles
#  ansible.builtin.command: "./install_dotfiles.sh"
#  args:
#    chdir: "{{ dotfiles.destination }}"
#  become: true
#  become_user: "{{ user.name }}"
#  
