---

- name: Install lightdm and components
  community.general.pacman:
    name:
      - lightdm
      - lightdm-gtk-greeter
      - lightdm-gtk-greeter-settings
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Copy lightdm configs
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/lightdm/
    owner: root
    group: root
  with_items:
    - lightdm.conf
    - Xsession
    - slick-greeter.conf
    - lightdm-gtk-greeter.conf

  
