---

- name: Install alsa-utils and pipewire tools
  community.general.pacman:
    name:
      - alsa-utils
      - alsa-firmware
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - wireplumber
      - pamixer
      - pavucontrol
      - pulsemixer
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: create directory for pulse
  ansible.builtin.file:
    path: "/home/{{ user.name }}/.config/pulse"
    state: directory
    owner: "{{ user.name }}"

- name: Deploy HiFi pulse audio daemon configuration
  ansible.builtin.template:
    src: daemon.conf.j2
    dest: "/home/{{ user.name }}/.config/pulse/daemon.conf"
  become_user: "{{ user.name }}"
  become: true


- name: Install Audio and Music tools
  community.general.pacman:
    name:
      - ffmpeg
      - ffmpegthumbnailer
      - mpd
      - mpc
      - mpv
      - mediainfo
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
