---

- name: Install Apparmor
  community.general.pacman:
    name:
      - apparmor
      - audit
      - python-notify2
      - tk
      - dex
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: enable apparmor service
  ansible.builtin.service:
    name: apparmor
    state: started
    enabled: true

- name: enable audit service
  ansible.builtin.service:
    name: auditd
    state: started
    enabled: true

- name: Enable Audit Notifications
  ansible.builtin.copy:
    src: audit-notify.desktop
    dest: /home/{{ user.name }}/.config/autostart/audit-notify.desktop
    owner: "{{ user.name }}"
    group: "{{ user.name }}"


- name: activate cache modus apparmor
  ansible.builtin.lineinfile:
    path: /etc/apparmor/parser.conf
    state: present
    line: "{{ item }}"
  loop:
    - "## Turn creating/updating of the cache on by default"
    - "write-cache"
