---

- name: disable dumps ulimit
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    state: present
    line: "{{ item }}"
  loop:
    - "* hard core 0"
    - "# Core dumps contain the recorded state of the working memory of a program at a specific time, usually when that program has crashed. These can contain very important information such as passwords and encryption keys. [45] You should disable these to prevent someone from accessing that information."

- name: Create directory/etc/systemd/coredump.conf.d
  ansible.builtin.file:
    path: /etc/systemd/coredump.conf.d
    state: directory

- name: Copy custom.conf to /etc/systemd/coredump.conf.d
  ansible.builtin.copy:
    src: custom.conf
    dest:  /etc/systemd/coredump.conf.d/custom.conf
    owner: root
    group: root