---

- name: Add IPv6 privacy settings for networkmanager
  ansible.builtin.lineinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    state: present
    line: "{{ item }}"
  loop:
    - "[connection]"
    - "ipv6.ip6-privacy=2"
    - "# to enable privacy extensions for NetworkManager"

- name: Copy ipv6.conf to /etc/systemd/network/
  ansible.builtin.copy:
    src: ipv6.conf
    dest:  /etc/systemd/network/ipv6.conf
    owner: root
    group: root