---

- name: import sysctl tasks
  ansible.builtin.import_tasks: sysctl.yml
    
- name: import apparmor tasks
  ansible.builtin.import_tasks: apparmor.yml

- name: import hideproc tasks
  ansible.builtin.import_tasks: hideproc.yml

- name: import dumps tasks
  ansible.builtin.import_tasks: dump.yml

- name: import ipv6 tasks
  ansible.builtin.import_tasks: ipv6.yml

- name: import modprobe tasks
  ansible.builtin.import_tasks: modprobe.yml

- name: import passwd tasks
  ansible.builtin.import_tasks: passwd.yml

  

