---

- name: Copy sysctl configs
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/sysctl.d/
    owner: root
    group: root
  with_items:
    - mmap_aslr.conf
    - ptrace_scope.conf
    - dmesg_restrict.conf  
    - sysrq.conf
    - harden_bpf.conf     
    - tcp_hardening.conf
    - kexec.conf
    - tcp_sack.conf
    - kptr_restrict.conf   
    - unprivileged_users_clone.conf
    - coredump.conf
    - suid_dumpable.conf
    - ipv6_privacy.conf