---

- name: Install secure arch linux environment
  hosts: hosts
  connection: local
  become: true

  roles:
    - { role: network, tags: ['network'] }
    - { role: kernel, tags: ['kernel'] }
    - { role: base, tags: ['base'] }
    - { role: firewall, tags: ['firewall'] }
    - { role: grub, tags: ['grub'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: terminal, tags: ['terminal'] }
    - { role: i3, tags: ['i3'], when: "windowmanager == 'i3'"}
    - { role: suckless, tags: ['suckless'], when: "windowmanager == 'suckless'"}	
    - { role: browsers, tags: ['browsers'] }
    - { role: redshift, tags: ['redshift'] }
    - { role: keepass, tags: ['keepass'] }
    - { role: macspoof, tags: ['macspoof'], when: "system.macspoof == 'enabled'"}
    - { role: sound, tags: ['sound'] }
    - { role: office, tags: ['office'] } 
    - { role: appearance, tags: ['appearance'] }
    - { role: monitor, tags: ['monitor'] }
