base_mirrors:
  - https://mirrors.niyawe.de/archlinux/$repo/os/$arch
  - https://mirror.pseudoform.org/$repo/os/$arch
  - https://arch.phinau.de/$repo/os/$arch
  - https://berlin.mirror.pkgbuild.com/$repo/os/$arch
  - https://de.arch.mirror.kescher.at/$repo/os/$arch
  - https://mirror.moson.org/arch/$repo/os/$arch
  - https://de.arch.niranjan.co/$repo/os/$arch
  - https://archlinux.thaller.ws/$repo/os/$arch

base_ntp_server: de.pool.ntp.org
